services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest

    container_name: mealie

    restart: always

    ports:
      - "9925:9000" 

    volumes:
      - mealie-data:/app/data/

    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 0
      PGID: 0
      TZ: America/Anchorage

volumes:
  mealie-data: