auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

# promtail-specific configuration (Loki ignores this)
# client configuration for Promtail to send logs to Loki
clients:
  - url: http://loki:3100/loki/api/v1/push

# where promtail reads logs from
scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        # Set to true to include all container logs, or false to exclude all and use a filter
        # refresh_interval: 5s # How often to re-evaluate containers

    relabel_configs:
      # Extract container name
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container_name

      # Extract image name
      - source_labels: ['__meta_docker_image']
        regex: '(.*)'
        target_label: image

      # Set job label to dockerlogs
      - source_labels: ['__meta_docker_container_name']
        regex: '(.+)'
        target_label: job
        replacement: dockerlogs