services:
  steamcmd_sf_downloader:
    image: cm2network/steamcmd
    container_name: steamcmd_sf_downloader
    volumes:
      - ./steamcmd_script.txt:/home/steam/steamcmd_script.txt
      - ./sf_server_data/server:/home/steam/sf_server
    command: /home/steam/steamcmd/steamcmd.sh +runscript /home/steam/steamcmd_script.txt
    restart: "no"
    user: "1000:1000"

  satisfactory_server:
    # We'll use a generic Linux base image here as we're setting it up manually
    # Often, 'ubuntu:latest' or 'debian:latest' are good choices for this.
    image: debian:stable-slim
    container_name: satisfactory_server
    depends_on:
      steamcmd_sf_downloader:
        condition: service_completed_successfully
    ports:
      - "7777:7777"
    volumes:
      # Mount the same data directory where SteamCMD put the files
      - ./sf_server_data/server:/opt/sf_server
    # environment:
      # You might also want to set the server's name here for easier identification in logs
      # SERVER_NAME: "My Awesome PZ Server"
    restart: always
    command: ./opt/sf_server/FactoryServer.sh
    user: "1000:1000"