services:
  grafana:
    extends:
      file: ./grafana/compose.yaml
      service: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring-net


  prometheus:
    extends:
      file: ./prometheus/compose.yaml
      service: prometheus
    expose:
      - "9090"
    # Not needed, link to grafana using service name ex: 'prometheus:9090'
    # ports:
    #   - "9090:9090" 
    networks:
      - monitoring-net
    # for access to node exporter *unsafe* 
    # create firewalls to block access to other ports not needed from docker networks
    extra_hosts:
      - "host.docker.internal:host-gateway"


  cadvisor:
    extends:
      file: ./cadvisor/compose.yaml
      service: cadvisor
    expose:
      - "8080"
    # Not needed, link to prometheus using service name ex: 'cadvisor:8080'
    # ports:
    #   - "8080:8080" 
    networks:
      - monitoring-net

      
  redis:
    image: redis:latest
    container_name: redis
    expose:
      - "6379"


networks:
  monitoring-net:
    driver: bridge


volumes:
  grafana_data: {}
  prometheus_data: {}