apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090 # Service name 'prometheus' in Docker Compose network
    access: proxy
    isDefault: true
    version: 1
    editable: true

  - name: Loki
    type: loki
    url: http://loki:3100 # Service name 'loki' in Docker Compose network
    access: proxy
    version: 1
    editable: true