services:
  steamcmd_pzd_downloader:
    image: cm2network/steamcmd
    container_name: steamcmd_pzd_downloader # Renamed for clarity
    volumes:
      - ./project_zomboid_server_data:/home/steam/pz_server # Dedicated volume for PZ
    command: /home/steam/steamcmd/steamcmd.sh +login anonymous +force_install_dir /home/steam/pz_server +app_update 380870 validate +quit
    restart: "no"

  project_zomboid_server:
    # We'll use a generic Linux base image here as we're setting it up manually
    # Often, 'ubuntu:latest' or 'debian:latest' are good choices for this.
    # For PZ, you'll need a Java runtime, so a Java-enabled base is ideal, or you install it.
    image: openjdk:17-jdk-slim # A common choice for Java-based servers like PZ
    container_name: project_zomboid_dedicated_server
    depends_on:
      - steamcmd_pzd_downloader
    ports:
      # Default PZ ports. You might need more if you have many players or specific mods.
      - "16261:16261/udp" # Game traffic
      - "16262:16262/udp" # Game traffic
      - "8766:8766/udp"   # Steam authentication
      - "8767:8767/udp"   # Steam authentication
    volumes:
      # Mount the same data directory where SteamCMD put the files
      - ./project_zomboid_server_data:/opt/pz_server
      # PZ also stores user data (saves, configs, logs) in the user's home directory.
      # It's highly recommended to mount this as a separate persistent volume.
      # The default location for PZ server data is usually ~/.cache/Server or ~/Zomboid/Server
      # We'll use a new volume for that here:
      - ./project_zomboid_user_data:/root/Zomboid # Assuming running as root, adjust if needed
    environment:
      # Project Zomboid typically requires Java memory arguments.
      # Adjust these based on your server's RAM.
      # For example, -Xms4g -Xmx8g means min 4GB, max 8GB.
      PZ_JAVA_OPTS: "-Xms1G -Xmx2G"
      # You might also want to set the server's name here for easier identification in logs
      # SERVER_NAME: "My Awesome PZ Server"
    restart: always
    # Project Zomboid server will typically be launched via a startup script.
    # We'll override this with 'bash' initially to allow manual setup.
    # After setup, you'll update this or use 'docker exec' to start the server.
    command: sleep infinity
