services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped

    command:
      - "--config.file=/etc/prometheus/config.yaml"

    volumes:
      - ./:/etc/prometheus
      - prometheus_data:/prometheus